apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g4ysgv16k-go 
  janus-idp.io/tekton: g4ysgv16k-go
  backstage.io/kubernetes-id: g4ysgv16k-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g4ysgv16k-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  