apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g4ysgv16k-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g4ysgv16k-go 
  name: g4ysgv16k-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: g4ysgv16k-go 
